---
image:
  repository: ghcr.io/martinweindel/cleanup-events/cleanup-events
  tag: latest
  pullPolicy: Always

name: cleanup-events-job
fullname: cleanup-events-job
restartPolicy: OnFailure

duration: "1h"
dryRun: false
